version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo search-photos part...
      - echo Zipping...
      - cd index-photos/packages
      - zip -r ../search-photos.zip .
      - cd ..
      - zip -g search-photos.zip lambda_function.py
      - ls
      - echo index-photos...
      - cd ../search-photos/packages
      - zip -r ../index-photos.zip .
      - cd ..
      - zip -g index-photos.zip lambda_function.py
    commands:
      - echo Updateing search-photos lambda function
      - aws lambda update-function-code --function-name "search-photos2" --zip-file fileb://search-photos.zip --region "us-west-2"
      - rm search-photos/search-photos.zip
      - echo search-photos Done!!
      - echo Updateing Index-photos lambda function
      - aws lambda update-function-code --function-name photoIndex2 --zip-file fileb://index-photos.zip --region "us-west-2"
      - rm index-photos/index-photos.zip
      - echo index photos Done!!
